# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sagungt.github.io v1

on:
  workflow_dispatch:
  push:
    branches: [ "v1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - name: Install packages ✔
      run: npm ci
      
    - name: Build 🧪
      run: npm run build
      
    - name: Deploy 🚀
      run: |
        cd dist
        git config --global user.name "sagungt"
        git config --global user.email "agungjordan.aj@gmail.com"
        git init
        git checkout -b main
        git add -A
        git commit -m "Deploy 🚀 with Github Actions"
        git push -f git@github.com:sagungt/sagungt.github.io.git main
