# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sagungt.github.io v1

on:
  workflow_dispatch:
  push:
    branches: 'v1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - name: Install packages ✔
      run: npm ci
      
    - name: Build 🧪
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: List directory
        run: ls -l
        
    
